### ISSUE TITLE
No module named "triton". how to fix?

### ISSUE THREAD

**Issue by moviejimmy** [sdbds/hallo-for-windows#3]
(venv) C:\Hallo\hallo-for-windows>python scripts/inference.py --source_image examples/reference_images/sammy.jpg --driving_audio examples/driving_audios/2.wav
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Hallo\hallo-for-windows\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Hallo\hallo-for-windows\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

**Comment by dreamhacking** [comment]
Same here :(
No module named 'triton'
No module named 'hallo'

O:\hallo-portable-2\webui\venv\lib\site-packages\transformers\utils\hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "O:\hallo-portable-2\webui\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "O:\hallo-portable-2\webui\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
Traceback (most recent call last):
  File "O:\hallo-portable-2\webui\scripts\inference.py", line 40, in <module>
    from hallo.animate.face_animate import FaceAnimatePipeline
ModuleNotFoundError: No module named 'hallo'

**Comment by dreamhacking** [comment]
this worked for me:
https://github.com/daswer123/hallo-webui/issues/16
